#
###################################
# Site wide configuration
####################################
#
title: UABCSSA
email: cssauab@gmail.com
description: "阿拉巴马大学伯明翰分校中国学生学者联合会"
url: https://uabcssa.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          US
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
# permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins: [jekyll-paginate]
paginate: 5

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: UAB 中国学生学者联合会
  avatar: UABCSSA_logo.png
  job: "at Birmingham, AL"
  bio: "UAB 中国学生学者联合会旨在为大家提供便利，分享租房，购物，美食，旅游，体育活动，二手交易等信息。并且我们为新生提供入学帮助，接机，安排短暂住宿等。"
  email: cssauab@gmail.com
  disqus-shortname:
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: uabcssa #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:  #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

